// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzvWES4EQ8BrCCnGojQ4sOEcbI9l6DHk4',
    appId: '1:828666375529:web:8010be8efd6422699961f8',
    messagingSenderId: '828666375529',
    projectId: 'sgx-online-qa',
    authDomain: 'sgx-online-qa.firebaseapp.com',
    storageBucket: 'sgx-online-qa.appspot.com',
    measurementId: 'G-C1X1SK5K8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgYRNXa95gmgHunhVVVBxE2LJsyDoIA5A',
    appId: '1:828666375529:android:e45fcc1e514821e59961f8',
    messagingSenderId: '828666375529',
    projectId: 'sgx-online-qa',
    storageBucket: 'sgx-online-qa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgYRNXa95gmgHunhVVVBxE2LJsyDoIA5A',
    appId: '1:828666375529:android:e45fcc1e514821e59961f8',
    messagingSenderId: '828666375529',
    projectId: 'sgx-online-qa',
    storageBucket: 'sgx-online-qa.appspot.com',
  );

}